# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "PHPStan"
on:
  pull_request:
    paths:
      - 'extractor/**'
      - '.github/workflows/phpstan.yml'
  push:
    branches:
      - "main"
    paths:
      - 'extractor/**'
      - '.github/workflows/phpstan.yml'

permissions:
  contents: read

jobs:
  phpstan:
    name: "PHPStan"
    runs-on: "ubuntu-latest"
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ccd8616d44fd3846e67624a50d5aad6d37bf2d25 # v2.22.1
        with:
          egress-policy: audit

      - name: "Checkout"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: "Install PHP"
        uses: "shivammathur/setup-php@eb7c497e18156a6bbabfef1d3a82760b9eda3962" # 2.40.0
        with:
          coverage: "none"
          php-version: "8.3"
      - name: "Install dependencies"
        run: "composer install"
        working-directory: ./extractor
      - name: "Run PHPStan"
        working-directory: ./extractor
        run: "vendor/bin/phpstan"
