# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "PHPStan"
on:
  pull_request:
    paths:
      - 'extractor/**'
      - '.github/workflows/phpstan.yml'
  push:
    branches:
      - "main"
    paths:
      - 'extractor/**'
      - '.github/workflows/phpstan.yml'

permissions:
  contents: read

jobs:
  phpstan:
    name: "PHPStan"
    runs-on: "ubuntu-latest"
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@58077d3c7e43986b6b15fba718e8ea69e387dfcc # v2.15.1
        with:
          egress-policy: audit

      - name: "Checkout"
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - name: "Install PHP"
        uses: "shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1" # v2
        with:
          coverage: "none"
          php-version: "8.3"
      - name: "Install dependencies"
        run: "composer install"
        working-directory: ./extractor
      - name: "Run PHPStan"
        working-directory: ./extractor
        run: "vendor/bin/phpstan"
