# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Create release"

on:
  push:
    tags:
      - '*'

concurrency: release

permissions:
  contents: read

jobs:
  deploy:
    permissions:
      contents: write  # for softprops/action-gh-release to create GitHub release
    name: "Deploy"
    runs-on: "ubuntu-latest"

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: "Checkout"
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: "Create release"
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65 # v2.6.2
        with:
          token: ${{ secrets.PHPSTAN_BOT_TOKEN }}
