# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Create release"

on:
  push:
    tags:
      - '*'

concurrency: release

permissions:
  contents: read

jobs:
  deploy:
    permissions:
      contents: write  # for softprops/action-gh-release to create GitHub release
    name: "Deploy"
    runs-on: "ubuntu-latest"

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@58077d3c7e43986b6b15fba718e8ea69e387dfcc # v2.15.1
        with:
          egress-policy: audit

      - name: "Checkout"
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: "Create release"
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
          token: ${{ secrets.PHPSTAN_BOT_TOKEN }}
