# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Update stubs"
on:
  push:
    branches:
      - "main"
  schedule:
    # * is a special character in YAML so you have to quote this string
      - cron: '0 0 * * *'

jobs:
  update:
    name: "Update stubs"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: '0'
      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "7.4"
          tools: composer:v2
      - name: "Install dependencies"
        run: "composer install"
        working-directory: ./extractor
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          repository: "php/php-src"
          path: "php-src"
      - name: "Extract stubs"
        run: "./extractor/extract.php"
      - name: "Commit changes"
        uses: "stefanzweifel/git-auto-commit-action@v4"
        id: "commit"
        with:
          commit_message: "Update stubs"
          commit_user_name: phpstan
          commit_user_email: actions@github.com
          commit_author: PHPStan Bot <actions@github.com>
      - name: "Tag new version"
        if: steps.commit.outputs.changes_detected == 'true'
        id: "tag"
        uses: "anothrNick/github-tag-action@1.30.0"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          RELEASE_BRANCHES: main
          DEFAULT_BUMP: patch
      - name: "Release new version"
        if: steps.commit.outputs.changes_detected == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.new_tag }}
          release_name: ${{ steps.tag.outputs.new_tag }}
          commitish: main
          body: "Update stubs"
